const 
    LISTCONTEXT_OPEN_CONTEXT_MENU = 0,
    LISTCONTEXT_CLOSE_CONTEXT_MENU = 1,
    LISTCONTEXT_ROW_CLICKED = 2,
    LISTCONTEXT_CLEAR_SELECTION = 3,
    LISTCONTEXT_SETDRAGGEDOVERITEM = 4,
    LISTCONTEXT_CLEARDRAGGEDOVERITEM = 5;

export {
    LISTCONTEXT_OPEN_CONTEXT_MENU,
    LISTCONTEXT_CLOSE_CONTEXT_MENU,
    LISTCONTEXT_ROW_CLICKED,
    LISTCONTEXT_CLEAR_SELECTION,
    LISTCONTEXT_SETDRAGGEDOVERITEM,
    LISTCONTEXT_CLEARDRAGGEDOVERITEM
}